### ISSUE TITLE
Running ./genbinding.sh on macOS gets stuck for a really long time

### ISSUE THREAD

**Issue by jurvis** [lightningdevkit/ldk-c-bindings#76]
Not a deal-breaker, but I noticed that whenever the build log reaches `set +x`, nothing really happens beyond that. 

According to @arik-so it's usually fine past that point to just force the shell script to terminate, but I was wondering if there is a fix for this so CI over at `ldk-swift` doesn't take ages to run.

**Comment by arik-so** [comment]
It's a bug with Mac's regex engine in the following command. On Linux this runs much faster whereas on Mac you need to wait like 20 minutes.

**Comment by jurvis** [comment]
gah. sad.

**Comment by jurvis** [comment]
is there a radar filed for it? where can I read more about the bug?

**Comment by jurvis** [comment]
Here's the output I get from running GNU sed:

```
+ sed -E -i '' 's|#*lightning = \{ .*|lightning = \{ path = "/Users/jurvistest/Projects/ldk/ldk-swift/bindings/artifacts/rust-lightning/lightning", default-features = false }|' lightning-c-bindings/Cargo.toml
sed: can't read s|#*lightning = \{ .*|lightning = \{ path = "/Users/jurvistest/Projects/ldk/ldk-swift/bindings/artifacts/rust-lightning/lightning", default-features = false }|: No such file or directory
```

It sounds like I'm missing some type of configuration? I'm not familiar with `sed` so can't say at a glance what it is.

**Comment by jurvis** [comment]
ah, okay, i see the code that differentiates the args here now https://github.com/lightningdevkit/ldk-c-bindings/blob/main/genbindings.sh#L158-L163

**Comment by jurvis** [comment]
#77 makes an attempt to use GNU sed which takes compilation time on macOS down from 20 to 5 minutes. Closing issue.
